language: go

go:
  - 1.5.1

services:
  - redis-server
  - mysql
  - postgresql
  - memcached
env:
  - ORM_DRIVER=sqlite
  - ORM_DRIVER=mysql
  - ORM_DRIVER=postgres
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then export ORM_SOURCE='user=postgres dbname=orm_test sslmode=disable'; psql -c 'create database orm_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then export ORM_SOURCE='root:@/orm_test?charset=utf8'; mysql -u root -e 'create database orm_test;'; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then export ORM_SOURCE=$TRAVIS_BUILD_DIR/orm_test.db; touch $TRAVIS_BUILD_DIR/orm_test.db; fi"
